#!/bin/bash

source ./config

for i in $EXAMPLES/*.cpp; do
#  mex CXXFLAGS="$CXXFLAGS -I$LIB" $i -outdir $OUT
#  mex CXXFLAGS="$CXXFLAGS" $i -outdir $OUT
  BASE=${i:${#EXAMPLES}:-4}
  # echo $OUT/$BASE.mexa64
  # echo $i
  if [ $i -nt $OUT/$BASE.mexa64 ]; then
    mex CXXFLAGS="$CXXFLAGS" $i -outdir $OUT
  fi
done
